CREATE TABLE EMOTION
(
    EMOTION_CODE NUMBER(1) PRIMARY KEY,
    EMOTION_NAME VARCHAR2(6)
);

CREATE TABLE MUSIC
(
    SONG_NAME VARCHAR2(200),
    SINGER VARCHAR2(200),
    EMOTION_CODE NUMBER(1),
    
    CONSTRAINT FK_EMOTION FOREIGN KEY(EMOTION_CODE)
    REFERENCES EMOTION(EMOTION_CODE)
);

INSERT INTO EMOTION (EMOTION_CODE, EMOTION_NAME) VALUES (1, 'happy');
INSERT INTO EMOTION (EMOTION_CODE, EMOTION_NAME) VALUES (2, 'sad');
INSERT INTO EMOTION (EMOTION_CODE, EMOTION_NAME) VALUES (3, 'mad');